version: "3.8"

networks:
    bridge:
        driver: bridge

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:6.1.1
        environment: 
            ZOOKEEPER_CLIENT_PORT: 32181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            bridge:
                aliases: 
                    - zookeeper
    
    kafka:
        image: wurstmeister/kafka:2.11-1.1.1
        depends_on: 
            - zookeeper
        environment: 
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            JMX_PORT: 9999
        networks:
            bridge:
                aliases:
                    - kafka
        restart: always
    
    kafka-manager:
        image: sheepkiller/kafka-manager:latest
        environment:
            ZK_HOSTS: "zookeeper:32181"
        ports:
            - 9000:9000
        networks:
            - bridge
        restart: always

    nifi:
        image: apache/nifi:1.13.2
        depends_on: 
            - kafka
        ports:
            - 8080:8080
        restart: always
        volumes:
            - ~/Projects/data-challenge/nifi/ls-target:/opt/nifi/nifi-current/ls-target
        