version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    ports:
      - "2181:2181"
    
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    hostname: kafka
    depends_on: 
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: crypto:1:1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://127.0.0.1:9094
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
  kafka-producer:
    build: .
    depends_on:
      - kafka
    environment: 
      APP_GOAL: producer
      APP_KAFKA_TOPIC: crypto
      APP_KAFKA_SERVER: kafka:9092
      APP_ZOOKEEPER_SERVER: zookeeper:2181
      APP_PRODUCER_INTERVAL: 100

  # spark-consumer:
  #   build: .
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "4040:4040"
  #   environment: 
  #     APP_GOAL: consumer
  #     APP_KAFKA_TOPIC: netflix
  #     APP_KAFKA_SERVER: kafka:9092
  #     APP_ZOOKEEPER_SERVER: zookeeper:2181